name: controle_estoque_app
description: "A new Flutter project."

# Impede a publicação acidental no pub.dev
publish_to: "none"

# Definição da versão do aplicativo
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

  # Dependências do projeto
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.0
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.4
  flutter_native_splash: ^2.4.4

# Comando para gerar o splash screen
#   dart run flutter_native_splash:create

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_image.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo-dark.svg
    - assets/images/logo-light.svg
    - assets/images/estoque.png
    - assets/images/default-light.png
    - assets/images/default-light-user.png
    - assets/images/default-dark.png
    - assets/images/icone1.svg
    - assets/images/icone2.svg
    - assets/images/CaixaDoValor.svg
    - assets/images/Seta.svg
    - assets/images/Logo.png
    - assets/images/iconeEstoque.png
    - assets/images/iconeProdutos.png
    - assets/images/perfil.png
    - assets/images/iconeSair.png
    - assets/images/forgot-password.svg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 600
        - asset: assets/fonts/poppins.bold.ttf
          weight: 700
